/**
 * Keeta Dubai — settlement payout extractor
 *
 * Flow:
 *   1. Playwright loads /web/app/finance (headless) to warm up mtgsig anti-bot token
 *   2. page.evaluate() calls /api/settlement/statement/v2/r/download/task/list
 *      → returns S3 download URLs for settlement Excel files (per shop, per period)
 *   3. Each Excel is downloaded from S3 (no auth — pre-signed URLs)
 *   4. Invoice Details sheet is parsed:
 *        col H = "Payable to Restaurant" (net payout per day)
 *        col J = Billing Cycle (e.g. "2026.07.01~2026.07.07")
 *        col K = Settlement Date (actual bank transfer date)
 *   5. Rows are grouped by (shop_id, billing_cycle) → sum col H → 1 record per settlement
 *   6. POST each record to /api/keeta/portal-payout-record (backend deduplicates by payout_id)
 *
 * Session note: mtgsig is generated by H5guard JS running inside the browser.
 * Direct HTTP without it returns 403 on the download/task/list endpoint.
 * The session token (cookies) is valid until 2027-02.
 *
 * Usage (local):
 *   WEBHOOK_URL=https://sushizen-shift-app-038d846023bc.herokuapp.com \
 *   SESSION_PATH=scripts/keeta/keeta-session.b64.txt \
 *   node scripts/keeta/get-payouts.js
 *
 * Usage (CI):
 *   KEETA_SESSION=<base64> WEBHOOK_URL=... node scripts/keeta/get-payouts.js
 */

const { chromium }  = require('playwright');
const fs            = require('fs');
const path          = require('path');
const zlib          = require('zlib');
const xlsx          = require('xlsx');  // npm install xlsx

const WEBHOOK_URL   = process.env.WEBHOOK_URL;
const PORTAL        = 'https://merchant.mykeeta.com';

// Shop ID → store code mapping (Keeta portal shopIds)
// Which brand this run's session belongs to. Keeta gives each brand its own login,
// so the account decides the brand — the settlement report itself never says it.
const KEETA_BRAND = (process.env.KEETA_BRAND || 'sushi_zen').trim().toLowerCase();

const BRAND_PREFIX = { sushi_zen: 'SZ', ramen_zen: 'RZ', all_veggie: 'AVS' };

// The portal's shop label ("Arjan") → the branch code the rest of the OS uses.
const BRANCH_FROM_LABEL = [
  [/arjan/i,                    'ARJ'],
  [/barsha\s*3|al\s*barsha/i,   'AB3'],
  [/business\s*bay/i,           'BB'],
  [/jumeirah|jlt/i,             'JLT'],
  [/al\s*mina|mina/i,           'AM'],
  [/mirdif|mc/i,                'MC'],
];

function branchFromLabel(label) {
  for (const [re, code] of BRANCH_FROM_LABEL) if (re.test(label || '')) return code;
  return '';
}

/**
 * Identify a shop. SHOP_MAP wins so existing store codes never move; anything else is
 * built from this run's brand plus the label in the report. Skipping unknown shops is
 * what silently lost an entire brand's payouts, so only give up when the label cannot
 * be recognised either — and say so loudly.
 */
function resolveShop(shopId, shopLabel) {
  const known = SHOP_MAP[shopId];
  if (known) return known;
  const prefix = BRAND_PREFIX[KEETA_BRAND];
  const branch = branchFromLabel(shopLabel);
  if (!prefix || !branch) return null;
  return {
    code:  `KEETA_${prefix}_${branch}`,
    name:  `${KEETA_BRAND} ${shopLabel}`.trim(),
    brand: KEETA_BRAND,
    derived: true,
  };
}

const SHOP_MAP = {
  '1644178222': { code: 'KEETA_SZ_ARJ', name: 'Sushi ZEN Arjan',            brand: 'sushi_zen' },
  '1644171212': { code: 'KEETA_SZ_AB3', name: 'Sushi ZEN Al Barsha 3',       brand: 'sushi_zen' },
  '1644198211': { code: 'KEETA_SZ_BB',  name: 'Sushi ZEN Business Bay',      brand: 'sushi_zen' },
  '1644191210': { code: 'KEETA_SZ_JLT', name: 'Sushi ZEN Jumeirah Lake',     brand: 'sushi_zen' },
  '1644184196': { code: 'KEETA_SZ_AM',  name: 'Sushi ZEN Al Mina',           brand: 'sushi_zen' },

  // Ramen ZEN. Reports older than about June 2026 leave the shop-label column
  // blank, so label-based derivation cannot identify them and a year of history
  // was being skipped. The ids are stable, so map them outright.
  '1644200182': { code: 'KEETA_RZ_ARJ', name: 'Ramen ZEN Arjan',             brand: 'ramen_zen' },
  '1644320430': { code: 'KEETA_RZ_AB3', name: 'Ramen ZEN Al Barsha 3',       brand: 'ramen_zen' },
  '1644173192': { code: 'KEETA_RZ_BB',  name: 'Ramen ZEN Business Bay',      brand: 'ramen_zen' },
  '1644193201': { code: 'KEETA_RZ_JLT', name: 'Ramen ZEN Jumeirah Lake',     brand: 'ramen_zen' },
  '1644179577': { code: 'KEETA_RZ_AM',  name: 'Ramen ZEN Al Mina',           brand: 'ramen_zen' },
};

// Brand id used by the portal's own "All restaurants" selection. One report per
// period covers every shop — the Excel carries a Restaurant ID column, so the
// parser splits them apart without needing a task per shop.
const BRAND_INPUT_ID = 297253;

// ── Report generation ────────────────────────────────────────────────────────

/** Calendar months overlapping [from, to], as GST day boundaries in epoch ms. */
function monthWindows(fromISO, toISO) {
  const out = [];
  const start = new Date(`${fromISO}T00:00:00+04:00`);
  const end   = new Date(`${toISO}T00:00:00+04:00`);
  let y = start.getUTCFullYear(), m = start.getUTCMonth();
  while (true) {
    const first = new Date(Date.UTC(y, m, 1));
    const last  = new Date(Date.UTC(y, m + 1, 0));
    if (first > end) break;
    const iso = (d) => d.toISOString().slice(0, 10);
    out.push({
      label: iso(first).slice(0, 7),
      startStamp: Date.parse(`${iso(first)}T00:00:00.000+04:00`),
      endStamp:   Date.parse(`${iso(last)}T23:59:59.999+04:00`),
    });
    m += 1; if (m > 11) { m = 0; y += 1; }
  }
  return out;
}

/**
 * Ask Keeta to build the billing reports we need.
 *
 * Nothing can be imported for a period the portal has never generated — the
 * gaps in ar_payouts matched the months nobody had clicked Submit for. This
 * does that clicking.
 */
async function generateReports(page, fromISO, toISO) {
  const windows = monthWindows(fromISO, toISO);
  console.log(`\nRequesting billing reports for ${windows.length} month(s): ${fromISO} → ${toISO}`);

  let created = 0;
  for (const w of windows) {
    const res = await page.evaluate(async ([startStamp, endStamp, inputId]) => {
      const resp = await fetch(
        '/api/settlement/statement/v2/w/download/task/create?yodaReady=h5&csecplatform=4&csecversion=3.5.1',
        {
          method:  'POST',
          headers: { 'Content-Type': 'application/json' },
          body:    JSON.stringify({
            periodStartDateStamp: startStamp,
            periodEndDateStamp:   endStamp,
            type:                 2,
            inputIds:             [inputId],
            downloadTaskType:     3,
          }),
        }
      );
      return resp.json();
    }, [w.startStamp, w.endStamp, BRAND_INPUT_ID]).catch(e => ({ error: e.message }));

    if (res && res.code === 0) { console.log(`  ✓ ${w.label}`); created++; }
    else console.warn(`  ⚠ ${w.label}: ${JSON.stringify(res).slice(0, 160)}`);

    // The portal builds these server-side; don't hammer it.
    await page.waitForTimeout(2500);
  }
  return created;
}

/** Wait until nothing is still generating, so every file has a download URL. */
async function waitForGeneration(page, timeoutMs = 240_000) {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    const r = await page.evaluate(async () => {
      const resp = await fetch(
        '/api/settlement/statement/v2/r/download/task/list?yodaReady=h5&csecplatform=4&csecversion=3.5.1',
        { method: 'POST', headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ pageNo: 1, pageSize: 50, taskTypeList: [3] }) }
      );
      return resp.json();
    }).catch(() => null);

    const tasks = (r && r.data && r.data.pageContent) || [];
    const pending = tasks.filter(t => t.taskStatus !== 30).length;
    if (pending === 0) return true;
    console.log(`  ${pending} still generating…`);
    await page.waitForTimeout(10_000);
  }
  console.warn('  ⚠ Gave up waiting; some reports may not be ready this run');
  return false;
}

// ── Session ──────────────────────────────────────────────────────────────────

function loadSession() {
  const b64Env = process.env.KEETA_SESSION;
  if (b64Env) {
    const buf = Buffer.from(b64Env.trim(), 'base64');
    const raw = (buf[0] === 0x1f && buf[1] === 0x8b)
      ? zlib.gunzipSync(buf).toString('utf8')
      : buf.toString('utf8');
    const data = JSON.parse(raw);
    console.log(`✓ Session from KEETA_SESSION (${data.cookies?.length} cookies)`);
    return data;
  }
  const filePath = process.env.SESSION_PATH ||
                   path.join(__dirname, 'keeta-session.b64.txt');
  if (fs.existsSync(filePath)) {
    const raw = fs.readFileSync(filePath, 'utf8').trim();
    const buf = Buffer.from(raw, 'base64');
    const json = (buf[0] === 0x1f && buf[1] === 0x8b)
      ? zlib.gunzipSync(buf).toString('utf8')
      : buf.toString('utf8');
    const data = JSON.parse(json);
    console.log(`✓ Session from ${filePath} (${data.cookies?.length} cookies)`);
    return data;
  }
  // Fall back to plain JSON
  const jsonPath = path.join(__dirname, 'keeta-session.json');
  if (fs.existsSync(jsonPath)) {
    const data = JSON.parse(fs.readFileSync(jsonPath, 'utf8'));
    console.log(`✓ Session from ${jsonPath} (${data.cookies?.length} cookies)`);
    return data;
  }
  console.error('❌ No session. Run: node scripts/keeta/setup-session.js');
  process.exit(1);
}

// ── Webhook ──────────────────────────────────────────────────────────────────

async function postWebhook(endpoint, payload) {
  const url = `${WEBHOOK_URL}${endpoint}`;
  if (!WEBHOOK_URL) {
    console.log('  (dry run — no WEBHOOK_URL)');
    return { ok: true, dry_run: true };
  }
  const resp = await fetch(url, {
    method:  'POST',
    headers: { 'Content-Type': 'application/json' },
    body:    JSON.stringify(payload),
    signal:  AbortSignal.timeout(15_000),
  });
  if (!resp.ok) {
    const t = await resp.text().catch(() => '');
    throw new Error(`Webhook ${resp.status}: ${t.slice(0, 200)}`);
  }
  return resp.json();
}

// ── Excel parsing ─────────────────────────────────────────────────────────────

/**
 * Parse the "Invoice Details" sheet of a Keeta settlement Excel.
 * Returns: [{ shop_id, shop_code, billing_cycle, settlement_date, payout_aed }]
 * One entry per (shop_id × billing_cycle) combination.
 *
 * Sheet columns (row 1 = header):
 *   D (4)  = Restaurant ID (shop_id)
 *   E (5)  = shop code (portal label like "Arjan")
 *   H (8)  = Payable to Restaurant (AED, net payout for that day)
 *   J (10) = Billing Cycle ("2026.07.01~2026.07.07")
 *   K (11) = Settlement Date ("9 Jul 2026")
 */
function parseInvoiceDetails(wb) {
  const ws = wb.Sheets['Invoice Details'];
  if (!ws) return [];

  const rows = xlsx.utils.sheet_to_json(ws, { header: 1, raw: false });
  if (rows.length < 2) return [];

  // Group by (shop_id, billing_cycle)
  const groups = {};

  for (let i = 1; i < rows.length; i++) {
    const row = rows[i];
    if (!row || !row[3]) continue;          // col D = Restaurant ID
    const shopId       = String(row[3]).replace(/\.0$/, '').trim();
    const billingCycle = (row[9] || '').trim();     // col J
    const settlDate    = (row[10] || '').trim();    // col K
    // The "All restaurants" export formats amounts with thousands separators
    // ("1,056.22") while the per-shop one does not. parseFloat stops at the
    // comma, so 1,056.22 silently became 1 — a plausible-looking number, not an
    // error. Strip separators before parsing.
    const payable      = parseFloat(String(row[7] ?? '').replace(/,/g, '')) || 0;   // col H

    if (!shopId || !billingCycle || isNaN(payable)) continue;

    const key = `${shopId}||${billingCycle}`;
    if (!groups[key]) {
      groups[key] = {
        shop_id:         shopId,
        // Column E carries the portal's own label for the shop ("Arjan"). Keeping it
        // lets a restaurant that is not yet in SHOP_MAP still be identified, instead
        // of being dropped the way the whole Ramen ZEN account was.
        shop_label:      String(row[4] ?? '').trim(),
        billing_cycle:   billingCycle,
        settlement_date: settlDate,
        payout_aed:      0,
      };
    }
    groups[key].payout_aed += payable;
  }

  return Object.values(groups).map(g => ({
    ...g,
    payout_aed: Math.round(g.payout_aed * 100) / 100,
  }));
}

/**
 * Format billing cycle "2026.07.01~2026.07.07" → { start: "2026-07-01", end: "2026-07-07" }
 */
function parseCycle(cycleStr) {
  const m = cycleStr.match(/(\d{4})\.(\d{2})\.(\d{2})~(\d{4})\.(\d{2})\.(\d{2})/);
  if (!m) return { start: cycleStr, end: cycleStr };
  return {
    start: `${m[1]}-${m[2]}-${m[3]}`,
    end:   `${m[4]}-${m[5]}-${m[6]}`,
  };
}

/**
 * Parse "9 Jul 2026" → "2026-07-09"
 */
function parseSettlementDate(dateStr) {
  if (!dateStr) return null;
  try {
    // xlsx raw=false returns "9 Jul 2026" format
    const d = new Date(dateStr + ' UTC');
    if (isNaN(d.getTime())) return dateStr;
    return d.toISOString().slice(0, 10);
  } catch (_) {
    return dateStr;
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('\nKeeta Dubai settlement payout extractor');
  console.log('='.repeat(60));

  const sessionData = loadSession();
  const tmpSession  = path.join(__dirname, 'keeta-session-tmp.json');
  fs.writeFileSync(tmpSession, JSON.stringify(sessionData));

  const extractedAt = new Date().toISOString();

  // ── 1. Playwright: load finance page + call task/list via page.evaluate() ──
  console.log('\nLoading Keeta finance page (Playwright headless)...');
  const browser = await chromium.launch({ headless: true });
  const context  = await browser.newContext({ storageState: tmpSession });
  const page     = await context.newPage();

  await page.goto(`${PORTAL}/web/app/finance`, {
    waitUntil: 'networkidle',
    timeout:   45_000,
  }).catch(() => {});
  await page.waitForTimeout(4000);

  const currentUrl = page.url();
  console.log(`  Landed: ${currentUrl.replace(PORTAL, '')}`);

  if (currentUrl.includes('/login') || currentUrl.includes('identity.')) {
    console.error('\n❌ SESSION_EXPIRED — run: node scripts/keeta/setup-session.js');
    await browser.close();
    try { fs.unlinkSync(tmpSession); } catch (_) {}
    // Exiting 0 here kept the daily workflow green while it imported nothing.
    // Grab's ran and reported success every morning for six days after the
    // session died, so the one signal anybody was watching said the opposite
    // of the truth. An expired session is not a code bug, but it is a failed
    // run, and the check should say so.
    process.exit(1);
  }

  // ── 1b. Make sure the reports we want actually exist ────────────────────
  // Default to the last ~5 weeks so a routine run picks up newly closed cycles;
  // GENERATE_FROM/GENERATE_TO widen it for a backfill.
  const gstToday = new Date(Date.now() + 4 * 3600_000).toISOString().slice(0, 10);
  const genFrom  = process.env.GENERATE_FROM ||
    new Date(Date.now() + 4 * 3600_000 - 35 * 86400_000).toISOString().slice(0, 10);
  const genTo    = process.env.GENERATE_TO || gstToday;

  if (process.env.SKIP_GENERATE === '1') {
    console.log('\nSKIP_GENERATE=1 — using only reports that already exist');
  } else {
    const created = await generateReports(page, genFrom, genTo);
    if (created > 0) {
      console.log('  Waiting for Keeta to build them...');
      await waitForGeneration(page);
    }
  }

  // Call download/task/list via page.evaluate() (inherits mtgsig from page context)
  console.log('  Fetching download task list...');
  const taskResult = await page.evaluate(async () => {
    const resp = await fetch(
      '/api/settlement/statement/v2/r/download/task/list?yodaReady=h5&csecplatform=4&csecversion=3.5.1',
      {
        method:  'POST',
        headers: { 'Content-Type': 'application/json' },
        body:    JSON.stringify({ pageNo: 1, pageSize: 200, taskTypeList: [3] }),
      }
    );
    return resp.json();
  }).catch(e => ({ error: e.message }));

  await browser.close();
  try { fs.unlinkSync(tmpSession); } catch (_) {}

  if (taskResult.error || taskResult.code !== 0) {
    console.error('❌ Failed to fetch task list:', JSON.stringify(taskResult).slice(0, 300));
    process.exit(1);
  }

  const tasks = (taskResult.data && taskResult.data.pageContent) || [];
  console.log(`✓ ${tasks.length} settlement download tasks found`);

  // ── 2. Keep every finished report ───────────────────────────────────────
  // "All restaurants" files used to be skipped, but the parser reads the
  // Restaurant ID column out of each row, so one of those covers all five
  // shops — and it is what generateReports() asks for.
  const shopTasks = tasks.filter(t => t.taskStatus === 30 && t.downloadUrl);
  console.log(`  ${shopTasks.length} completed tasks with a download URL`);

  // ── 3. Download each Excel and parse ─────────────────────────────────────
  let totalPosted  = 0;
  let totalSkipped = 0;
  let totalErrors  = 0;

  // Track seen (shop_id × billing_cycle) to avoid double-processing duplicates
  const seen = new Set();

  for (const task of shopTasks) {
    // Download Excel from S3
    let xlsxBuf;
    try {
      const resp = await fetch(task.downloadUrl, { signal: AbortSignal.timeout(30_000) });
      if (!resp.ok) throw new Error(`HTTP ${resp.status}`);
      xlsxBuf = Buffer.from(await resp.arrayBuffer());
    } catch (err) {
      console.error(`  ❌ Download failed for ${task.taskName}: ${err.message}`);
      totalErrors++;
      continue;
    }

    // Parse
    let wb;
    try {
      wb = xlsx.read(xlsxBuf, { type: 'buffer', cellDates: false });
    } catch (err) {
      console.error(`  ❌ Excel parse failed for ${task.taskName}: ${err.message}`);
      totalErrors++;
      continue;
    }

    const settlements = parseInvoiceDetails(wb);
    if (settlements.length === 0) {
      console.log(`  ⚠ No settlements parsed from ${task.taskName}`);
      continue;
    }

    console.log(`\n  ${task.taskName} → ${settlements.length} billing cycle(s):`);

    for (const s of settlements) {
      // One report can now hold several shops, so the mapping is per row.
      const shopInfo = resolveShop(s.shop_id, s.shop_label);
      if (!shopInfo) {
        console.log(`    ⚠ shop ${s.shop_id} ("${s.shop_label}") is not in SHOP_MAP and its `
                  + `label was not recognised — its payout is NOT being recorded. `
                  + `Add it to SHOP_MAP or extend BRANCH_FROM_LABEL.`);
        totalSkipped++;
        continue;
      }
      if (shopInfo.derived) {
        console.log(`    + shop ${s.shop_id} ("${s.shop_label}") → ${shopInfo.code} (derived from KEETA_BRAND=${KEETA_BRAND})`);
      }

      const dedupeKey = `${s.shop_id}||${s.billing_cycle}`;
      if (seen.has(dedupeKey)) continue;
      seen.add(dedupeKey);

      const cycle   = parseCycle(s.billing_cycle);
      const settlDt = parseSettlementDate(s.settlement_date);
      const payoutId = `keeta_${shopInfo.code}_${cycle.start.replace(/-/g, '')}`;

      console.log(`    ${cycle.start}~${cycle.end}  → AED ${s.payout_aed.toFixed(2)}  [paid ${settlDt}]`);

      try {
        const res = await postWebhook('/api/keeta/portal-payout-record', {
          payout_id:       payoutId,
          shop_id:         s.shop_id,
          store_code:      shopInfo.code,
          store_name:      shopInfo.name,
          brand:           shopInfo.brand,
          billing_cycle:   s.billing_cycle,
          cycle_start:     cycle.start,
          cycle_end:       cycle.end,
          payout_aed:      s.payout_aed,
          settlement_date: settlDt,
          task_name:       task.taskName,
          extracted_at:    extractedAt,
        });
        if (res.inserted) {
          console.log(`      ✓ inserted  payout_id=${payoutId}`);
          totalPosted++;
        } else {
          console.log(`      • already exists payout_id=${payoutId}`);
          totalSkipped++;
        }
      } catch (err) {
        console.error(`      ❌ ${err.message}`);
        totalErrors++;
      }
    }
  }

  console.log('\n' + '='.repeat(60));
  console.log(`✓ ${totalPosted} new records inserted`);
  if (totalSkipped) console.log(`  ${totalSkipped} already existed (skipped)`);
  if (totalErrors)  console.log(`  ${totalErrors} errors`);
  console.log('Done.');
}

main().catch(err => { console.error(err); process.exit(1); });
